class CountryCodes {
  static const List<Map<String, String>> countryList = [
    {'code': '+93', 'name': 'Afghanistan', 'flag': '🇦🇫', 'shortForm': 'AF'},
    {'code': '+355', 'name': 'Albania', 'flag': '🇦🇱', 'shortForm': 'AL'},
    {'code': '+213', 'name': 'Algeria', 'flag': '🇩🇿', 'shortForm': 'DZ'},
    {'code': '+376', 'name': 'Andorra', 'flag': '🇦🇩', 'shortForm': 'AD'},
    {'code': '+244', 'name': 'Angola', 'flag': '🇦🇴', 'shortForm': 'AO'},
    {'code': '+54', 'name': 'Argentina', 'flag': '🇦🇷', 'shortForm': 'AR'},
    {'code': '+374', 'name': 'Armenia', 'flag': '🇦🇲', 'shortForm': 'AM'},
    {'code': '+61', 'name': 'Australia', 'flag': '🇦🇺', 'shortForm': 'AU'},
    {'code': '+43', 'name': 'Austria', 'flag': '🇦🇹', 'shortForm': 'AT'},
    {'code': '+994', 'name': 'Azerbaijan', 'flag': '🇦🇿', 'shortForm': 'AZ'},
    {'code': '+973', 'name': 'Bahrain', 'flag': '🇧🇭', 'shortForm': 'BH'},
    {'code': '+880', 'name': 'Bangladesh', 'flag': '🇧🇩', 'shortForm': 'BD'},
    {'code': '+375', 'name': 'Belarus', 'flag': '🇧🇾', 'shortForm': 'BY'},
    {'code': '+32', 'name': 'Belgium', 'flag': '🇧🇪', 'shortForm': 'BE'},
    {'code': '+501', 'name': 'Belize', 'flag': '🇧🇿', 'shortForm': 'BZ'},
    {'code': '+229', 'name': 'Benin', 'flag': '🇧🇯', 'shortForm': 'BJ'},
    {'code': '+975', 'name': 'Bhutan', 'flag': '🇧🇹', 'shortForm': 'BT'},
    {'code': '+591', 'name': 'Bolivia', 'flag': '🇧🇴', 'shortForm': 'BO'},
    {'code': '+387', 'name': 'Bosnia and Herzegovina', 'flag': '🇧🇦', 'shortForm': 'BA'},
    {'code': '+267', 'name': 'Botswana', 'flag': '🇧🇼', 'shortForm': 'BW'},
    {'code': '+55', 'name': 'Brazil', 'flag': '🇧🇷', 'shortForm': 'BR'},
    {'code': '+673', 'name': 'Brunei', 'flag': '🇧🇳', 'shortForm': 'BN'},
    {'code': '+359', 'name': 'Bulgaria', 'flag': '🇧🇬', 'shortForm': 'BG'},
    {'code': '+226', 'name': 'Burkina Faso', 'flag': '🇧🇫', 'shortForm': 'BF'},
    {'code': '+257', 'name': 'Burundi', 'flag': '🇧🇮', 'shortForm': 'BI'},
    {'code': '+855', 'name': 'Cambodia', 'flag': '🇰🇭', 'shortForm': 'KH'},
    {'code': '+237', 'name': 'Cameroon', 'flag': '🇨🇲', 'shortForm': 'CM'},
    {'code': '+238', 'name': 'Cape Verde', 'flag': '🇨🇻', 'shortForm': 'CV'},
    {'code': '+236', 'name': 'Central African Republic', 'flag': '🇨🇫', 'shortForm': 'CF'},
    {'code': '+235', 'name': 'Chad', 'flag': '🇹🇩', 'shortForm': 'TD'},
    {'code': '+56', 'name': 'Chile', 'flag': '🇨🇱', 'shortForm': 'CL'},
    {'code': '+86', 'name': 'China', 'flag': '🇨🇳', 'shortForm': 'CN'},
    {'code': '+57', 'name': 'Colombia', 'flag': '🇨🇴', 'shortForm': 'CO'},
    {'code': '+269', 'name': 'Comoros', 'flag': '🇰🇲', 'shortForm': 'KM'},
    {'code': '+242', 'name': 'Congo', 'flag': '🇨🇬', 'shortForm': 'CG'},
    {'code': '+506', 'name': 'Costa Rica', 'flag': '🇨🇷', 'shortForm': 'CR'},
    {'code': '+385', 'name': 'Croatia', 'flag': '🇭🇷', 'shortForm': 'HR'},
    {'code': '+53', 'name': 'Cuba', 'flag': '🇨🇺', 'shortForm': 'CU'},
    {'code': '+357', 'name': 'Cyprus', 'flag': '🇨🇾', 'shortForm': 'CY'},
    {'code': '+420', 'name': 'Czech Republic', 'flag': '🇨🇿', 'shortForm': 'CZ'},
    {'code': '+45', 'name': 'Denmark', 'flag': '🇩🇰', 'shortForm': 'DK'},
    {'code': '+253', 'name': 'Djibouti', 'flag': '🇩🇯', 'shortForm': 'DJ'},
    {'code': '+593', 'name': 'Ecuador', 'flag': '🇪🇨', 'shortForm': 'EC'},
    {'code': '+20', 'name': 'Egypt', 'flag': '🇪🇬', 'shortForm': 'EG'},
    {'code': '+503', 'name': 'El Salvador', 'flag': '🇸🇻', 'shortForm': 'SV'},
    {'code': '+372', 'name': 'Estonia', 'flag': '🇪🇪', 'shortForm': 'EE'},
    {'code': '+251', 'name': 'Ethiopia', 'flag': '🇪🇹', 'shortForm': 'ET'},
    {'code': '+358', 'name': 'Finland', 'flag': '🇫🇮', 'shortForm': 'FI'},
    {'code': '+33', 'name': 'France', 'flag': '🇫🇷', 'shortForm': 'FR'},
    {'code': '+995', 'name': 'Georgia', 'flag': '🇬🇪', 'shortForm': 'GE'},
    {'code': '+49', 'name': 'Germany', 'flag': '🇩🇪', 'shortForm': 'DE'},
    {'code': '+233', 'name': 'Ghana', 'flag': '🇬🇭', 'shortForm': 'GH'},
    {'code': '+30', 'name': 'Greece', 'flag': '🇬🇷', 'shortForm': 'GR'},
    {'code': '+852', 'name': 'Hong Kong', 'flag': '🇭🇰', 'shortForm': 'HK'},
    {'code': '+36', 'name': 'Hungary', 'flag': '🇭🇺', 'shortForm': 'HU'},
    {'code': '+91', 'name': 'India', 'flag': '🇮🇳', 'shortForm': 'IN'},
    {'code': '+62', 'name': 'Indonesia', 'flag': '🇮🇩', 'shortForm': 'ID'},
    {'code': '+98', 'name': 'Iran', 'flag': '🇮🇷', 'shortForm': 'IR'},
    {'code': '+964', 'name': 'Iraq', 'flag': '🇮🇶', 'shortForm': 'IQ'},
    {'code': '+353', 'name': 'Ireland', 'flag': '🇮🇪', 'shortForm': 'IE'},
    {'code': '+972', 'name': 'Israel', 'flag': '🇮🇱', 'shortForm': 'IL'},
    {'code': '+39', 'name': 'Italy', 'flag': '🇮🇹', 'shortForm': 'IT'},
    {'code': '+81', 'name': 'Japan', 'flag': '🇯🇵', 'shortForm': 'JP'},
    {'code': '+962', 'name': 'Jordan', 'flag': '🇯🇴', 'shortForm': 'JO'},
    {'code': '+254', 'name': 'Kenya', 'flag': '🇰🇪', 'shortForm': 'KE'},
    {'code': '+82', 'name': 'South Korea', 'flag': '🇰🇷', 'shortForm': 'KR'},
    {'code': '+965', 'name': 'Kuwait', 'flag': '🇰🇼', 'shortForm': 'KW'},
    {'code': '+961', 'name': 'Lebanon', 'flag': '🇱🇧', 'shortForm': 'LB'},
    {'code': '+60', 'name': 'Malaysia', 'flag': '🇲🇾', 'shortForm': 'MY'},
    {'code': '+52', 'name': 'Mexico', 'flag': '🇲🇽', 'shortForm': 'MX'},
    {'code': '+977', 'name': 'Nepal', 'flag': '🇳🇵', 'shortForm': 'NP'},
    {'code': '+64', 'name': 'New Zealand', 'flag': '🇳🇿', 'shortForm': 'NZ'},
    {'code': '+234', 'name': 'Nigeria', 'flag': '🇳🇬', 'shortForm': 'NG'},
    {'code': '+968', 'name': 'Oman', 'flag': '🇴🇲', 'shortForm': 'OM'},
    {'code': '+92', 'name': 'Pakistan', 'flag': '🇵🇰', 'shortForm': 'PK'},
    {'code': '+507', 'name': 'Panama', 'flag': '🇵🇦', 'shortForm': 'PA'},
    {'code': '+63', 'name': 'Philippines', 'flag': '🇵🇭', 'shortForm': 'PH'},
    {'code': '+48', 'name': 'Poland', 'flag': '🇵🇱', 'shortForm': 'PL'},
    {'code': '+351', 'name': 'Portugal', 'flag': '🇵🇹', 'shortForm': 'PT'},
    {'code': '+974', 'name': 'Qatar', 'flag': '🇶🇦', 'shortForm': 'QA'},
    {'code': '+7', 'name': 'Russia', 'flag': '🇷🇺', 'shortForm': 'RU'},
    {'code': '+966', 'name': 'Saudi Arabia', 'flag': '🇸🇦', 'shortForm': 'SA'},
    {'code': '+65', 'name': 'Singapore', 'flag': '🇸🇬', 'shortForm': 'SG'},
    {'code': '+27', 'name': 'South Africa', 'flag': '🇿🇦', 'shortForm': 'ZA'},
    {'code': '+34', 'name': 'Spain', 'flag': '🇪🇸', 'shortForm': 'ES'},
    {'code': '+94', 'name': 'Sri Lanka', 'flag': '🇱🇰', 'shortForm': 'LK'},
    {'code': '+46', 'name': 'Sweden', 'flag': '🇸🇪', 'shortForm': 'SE'},
    {'code': '+41', 'name': 'Switzerland', 'flag': '🇨🇭', 'shortForm': 'CH'},
    {'code': '+886', 'name': 'Taiwan', 'flag': '🇹🇼', 'shortForm': 'TW'},
    {'code': '+66', 'name': 'Thailand', 'flag': '🇹🇭', 'shortForm': 'TH'},
    {'code': '+90', 'name': 'Turkey', 'flag': '🇹🇷', 'shortForm': 'TR'},
    {'code': '+971', 'name': 'United Arab Emirates', 'flag': '🇦🇪', 'shortForm': 'AE'},
    {'code': '+44', 'name': 'United Kingdom', 'flag': '🇬🇧', 'shortForm': 'GB'},
    {'code': '+1', 'name': 'United States', 'flag': '🇺🇸', 'shortForm': 'US'},
    {'code': '+598', 'name': 'Uruguay', 'flag': '🇺🇾', 'shortForm': 'UY'},
    {'code': '+998', 'name': 'Uzbekistan', 'flag': '🇺🇿', 'shortForm': 'UZ'},
    {'code': '+58', 'name': 'Venezuela', 'flag': '🇻🇪', 'shortForm': 'VE'},
    {'code': '+84', 'name': 'Vietnam', 'flag': '🇻🇳', 'shortForm': 'VN'},
    {'code': '+263', 'name': 'Zimbabwe', 'flag': '🇿🇼', 'shortForm': 'ZW'},
  ];
}
