name: gibud
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+62
environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  carousel_slider: ^5.0.0
  iconsax: ^0.0.8
  logger: ^2.4.0
  url_launcher: ^6.3.0
  get_storage: ^2.1.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  change_app_package_name: ^1.4.0
  firebase_core: ^3.6.0
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  internet_connection_checker: ^1.0.0+1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  razorpay_flutter: ^1.4.0
  dio: ^5.7.0
  http: ^1.2.2
  cached_network_image: ^3.4.1
  fl_chart: ^0.69.0
  percent_indicator: ^4.2.3
  syncfusion_flutter_gauges: ^27.1.57
  image_picker: ^1.1.2
  video_player: ^2.9.2
  pdf: ^3.8.4
  path_provider: ^2.1.4
  share_plus: ^10.1.0
  google_generative_ai: ^0.4.6
  syncfusion_flutter_pdf: ^27.1.56
  screenshot: ^3.0.0
  sms_autofill: ^2.4.1
  google_sign_in: ^6.2.2
  crypto: ^3.0.6
  country_picker: ^2.0.27
  firebase_messaging: ^15.2.0
  flutter_dotenv: ^5.2.1
  onesignal_flutter: ^5.3.0
  cloud_functions: ^5.3.2
  zego_express_engine: ^3.21.0
  permission_handler: ^11.3.1
  zego_uikit_prebuilt_call: ^4.16.24
  firebase_storage: ^12.4.5
  chewie: ^1.11.3
  dotted_border: ^3.1.0
  mime: ^2.0.0
  path: ^1.9.1
  firebase_app_check: ^0.3.2+9
  flutter_svg: ^2.2.0
  flutter_animate: ^4.5.2
  animated_flip_counter: ^0.3.4
  flutter_chat_ui: ^2.8.1
  package_info_plus: ^8.3.0
#  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/gitbud_app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/gitbud_app_icon.png"
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onBoardingImages/
    - assets/images/splashScreenImage/
    - assets/images/surveyQuestionImages/
    - assets/images/
    - assets/images/loader_facts/
    - assets/logo/
    - assets/tongue_disease_classifier_rgb_v3_final.tflite
    - assets/labels.txt
    - assets/animations/
    - assets/fonts/open-sans/OpenSans-Regular.ttf
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

